MOVIES = [
    {
        "id": 1,
        "title": "Inception",
        "genre": "sci-fi",
        "mood": "mind-bending",
        "rating": 8.8,
        "duration": "long",
        "era": "modern",
        "language": "english",
        "description": "A thief who enters the dreams of others to steal secrets gets a chance at redemption.",
        "director": "Christopher Nolan",
        "year": 2010,
        "tags": ["dreams", "heist", "psychological", "action"],
        "poster_color": "#1a1a2e"
    },
    {
        "id": 2,
        "title": "The Shawshank Redemption",
        "genre": "drama",
        "mood": "inspiring",
        "rating": 9.3,
        "duration": "long",
        "era": "classic",
        "language": "english",
        "description": "Two imprisoned men bond over years, finding solace and eventual redemption.",
        "director": "Frank Darabont",
        "year": 1994,
        "tags": ["prison", "friendship", "hope", "drama"],
        "poster_color": "#2d1b69"
    },
    {
        "id": 3,
        "title": "Parasite",
        "genre": "thriller",
        "mood": "dark",
        "rating": 8.6,
        "duration": "medium",
        "era": "modern",
        "language": "foreign",
        "description": "A poor family schemes to become employed by a wealthy family, leading to shocking events.",
        "director": "Bong Joon-ho",
        "year": 2019,
        "tags": ["class", "social", "suspense", "korean"],
        "poster_color": "#0f3460"
    },
    {
        "id": 4,
        "title": "The Grand Budapest Hotel",
        "genre": "comedy",
        "mood": "whimsical",
        "rating": 8.1,
        "duration": "medium",
        "era": "modern",
        "language": "english",
        "description": "A famous concierge forms an unlikely bond with a lobby boy amid theft and war.",
        "director": "Wes Anderson",
        "year": 2014,
        "tags": ["quirky", "adventure", "comedy", "europe"],
        "poster_color": "#e94560"
    },
    {
        "id": 5,
        "title": "Interstellar",
        "genre": "sci-fi",
        "mood": "epic",
        "rating": 8.6,
        "duration": "long",
        "era": "modern",
        "language": "english",
        "description": "Astronauts travel through a wormhole near Saturn in search of a new home for humanity.",
        "director": "Christopher Nolan",
        "year": 2014,
        "tags": ["space", "science", "family", "emotional"],
        "poster_color": "#16213e"
    },
    {
        "id": 6,
        "title": "Amélie",
        "genre": "romance",
        "mood": "whimsical",
        "rating": 8.3,
        "duration": "medium",
        "era": "classic",
        "language": "foreign",
        "description": "A shy waitress decides to change the lives of those around her for the better.",
        "director": "Jean-Pierre Jeunet",
        "year": 2001,
        "tags": ["french", "quirky", "love", "charming"],
        "poster_color": "#4a0080"
    },
    {
        "id": 7,
        "title": "Mad Max: Fury Road",
        "genre": "action",
        "mood": "intense",
        "rating": 8.1,
        "duration": "medium",
        "era": "modern",
        "language": "english",
        "description": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler.",
        "director": "George Miller",
        "year": 2015,
        "tags": ["action", "post-apocalyptic", "chase", "feminist"],
        "poster_color": "#8b0000"
    },
    {
        "id": 8,
        "title": "The Godfather",
        "genre": "drama",
        "mood": "dark",
        "rating": 9.2,
        "duration": "long",
        "era": "classic",
        "language": "english",
        "description": "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
        "director": "Francis Ford Coppola",
        "year": 1972,
        "tags": ["mafia", "family", "power", "crime"],
        "poster_color": "#1a0a00"
    },
    {
        "id": 9,
        "title": "Spirited Away",
        "genre": "animation",
        "mood": "whimsical",
        "rating": 8.6,
        "duration": "medium",
        "era": "classic",
        "language": "foreign",
        "description": "A girl becomes trapped in a spirit world and must work to free herself and her parents.",
        "director": "Hayao Miyazaki",
        "year": 2001,
        "tags": ["anime", "fantasy", "japanese", "magical"],
        "poster_color": "#006400"
    },
    {
        "id": 10,
        "title": "Get Out",
        "genre": "thriller",
        "mood": "intense",
        "rating": 7.7,
        "duration": "short",
        "era": "modern",
        "language": "english",
        "description": "A Black man visits his white girlfriend's family estate and discovers disturbing secrets.",
        "director": "Jordan Peele",
        "year": 2017,
        "tags": ["horror", "social", "race", "psychological"],
        "poster_color": "#2c1810"
    },
    {
        "id": 11,
        "title": "Her",
        "genre": "romance",
        "mood": "mind-bending",
        "rating": 8.0,
        "duration": "medium",
        "era": "modern",
        "language": "english",
        "description": "A lonely writer falls in love with his AI operating system.",
        "director": "Spike Jonze",
        "year": 2013,
        "tags": ["ai", "love", "future", "loneliness"],
        "poster_color": "#cc4400"
    },
    {
        "id": 12,
        "title": "Knives Out",
        "genre": "comedy",
        "mood": "entertaining",
        "rating": 7.9,
        "duration": "medium",
        "era": "modern",
        "language": "english",
        "description": "A detective investigates the death of a patriarch of an eccentric, combative family.",
        "director": "Rian Johnson",
        "year": 2019,
        "tags": ["mystery", "whodunit", "comedy", "ensemble"],
        "poster_color": "#2e4a1e"
    },
]

BOOKS = [
    {
        "id": 1,
        "title": "Dune",
        "genre": "sci-fi",
        "mood": "epic",
        "length": "long",
        "era": "classic",
        "pace": "slow",
        "description": "A desert planet holds the universe's most precious resource. A young nobleman rises to lead.",
        "author": "Frank Herbert",
        "year": 1965,
        "pages": 688,
        "tags": ["politics", "religion", "ecology", "destiny"],
        "themes": ["power", "environment", "messianism"]
    },
    {
        "id": 2,
        "title": "The Name of the Wind",
        "genre": "fantasy",
        "mood": "epic",
        "length": "long",
        "era": "modern",
        "pace": "medium",
        "description": "A legendary wizard recounts his extraordinary life in his own words.",
        "author": "Patrick Rothfuss",
        "year": 2007,
        "pages": 662,
        "tags": ["magic", "music", "adventure", "revenge"],
        "themes": ["coming-of-age", "legend", "love"]
    },
    {
        "id": 3,
        "title": "Thinking, Fast and Slow",
        "genre": "non-fiction",
        "mood": "informative",
        "length": "medium",
        "era": "modern",
        "pace": "slow",
        "description": "Nobel laureate Kahneman reveals the two systems that drive the way we think.",
        "author": "Daniel Kahneman",
        "year": 2011,
        "pages": 499,
        "tags": ["psychology", "decision-making", "cognitive", "bias"],
        "themes": ["mind", "behavior", "economics"]
    },
    {
        "id": 4,
        "title": "The Hitchhiker's Guide to the Galaxy",
        "genre": "sci-fi",
        "mood": "humorous",
        "length": "short",
        "era": "classic",
        "pace": "fast",
        "description": "Seconds before Earth is destroyed, Arthur Dent is swept into a mad galactic adventure.",
        "author": "Douglas Adams",
        "year": 1979,
        "pages": 193,
        "tags": ["humor", "space", "absurd", "british"],
        "themes": ["existentialism", "satire", "friendship"]
    },
    {
        "id": 5,
        "title": "1984",
        "genre": "dystopian",
        "mood": "dark",
        "length": "medium",
        "era": "classic",
        "pace": "medium",
        "description": "In a totalitarian society, a man rebels against the oppressive ruling party.",
        "author": "George Orwell",
        "year": 1949,
        "pages": 328,
        "tags": ["surveillance", "totalitarianism", "rebellion", "truth"],
        "themes": ["freedom", "power", "love"]
    },
    {
        "id": 6,
        "title": "Atomic Habits",
        "genre": "self-help",
        "mood": "motivating",
        "length": "short",
        "era": "modern",
        "pace": "fast",
        "description": "Tiny changes, remarkable results. A proven framework for building good habits.",
        "author": "James Clear",
        "year": 2018,
        "pages": 320,
        "tags": ["productivity", "habits", "psychology", "self-improvement"],
        "themes": ["growth", "consistency", "identity"]
    },
    {
        "id": 7,
        "title": "The Remains of the Day",
        "genre": "literary-fiction",
        "mood": "melancholic",
        "length": "medium",
        "era": "classic",
        "pace": "slow",
        "description": "An English butler reflects on his years of service and the life he sacrificed for duty.",
        "author": "Kazuo Ishiguro",
        "year": 1989,
        "pages": 258,
        "tags": ["duty", "regret", "england", "reflection"],
        "themes": ["dignity", "repression", "missed-connections"]
    },
    {
        "id": 8,
        "title": "Project Hail Mary",
        "genre": "sci-fi",
        "mood": "hopeful",
        "length": "medium",
        "era": "modern",
        "pace": "fast",
        "description": "An astronaut wakes up alone millions of miles from home and must save Earth.",
        "author": "Andy Weir",
        "year": 2021,
        "pages": 476,
        "tags": ["survival", "science", "alien", "problem-solving"],
        "themes": ["friendship", "sacrifice", "ingenuity"]
    },
    {
        "id": 9,
        "title": "Sapiens",
        "genre": "non-fiction",
        "mood": "informative",
        "length": "medium",
        "era": "modern",
        "pace": "medium",
        "description": "A brief history of humankind, from ancient ancestors to modern society.",
        "author": "Yuval Noah Harari",
        "year": 2011,
        "pages": 443,
        "tags": ["history", "evolution", "culture", "civilization"],
        "themes": ["humanity", "progress", "meaning"]
    },
    {
        "id": 10,
        "title": "The Shadow of the Wind",
        "genre": "mystery",
        "mood": "dark",
        "length": "long",
        "era": "modern",
        "pace": "medium",
        "description": "A boy discovers a mysterious book in post-war Barcelona and becomes obsessed with its author.",
        "author": "Carlos Ruiz Zafón",
        "year": 2001,
        "pages": 487,
        "tags": ["spain", "mystery", "books", "gothic"],
        "themes": ["memory", "identity", "love"]
    },
    {
        "id": 11,
        "title": "Circe",
        "genre": "fantasy",
        "mood": "epic",
        "length": "medium",
        "era": "modern",
        "pace": "medium",
        "description": "The witch of Greek myth discovers her power and carves out a place in the world.",
        "author": "Madeline Miller",
        "year": 2018,
        "pages": 393,
        "tags": ["mythology", "feminism", "magic", "greek"],
        "themes": ["power", "isolation", "transformation"]
    },
    {
        "id": 12,
        "title": "Born a Crime",
        "genre": "memoir",
        "mood": "inspiring",
        "length": "short",
        "era": "modern",
        "pace": "fast",
        "description": "Trevor Noah's story of growing up during apartheid South Africa.",
        "author": "Trevor Noah",
        "year": 2016,
        "pages": 304,
        "tags": ["apartheid", "race", "south-africa", "humor"],
        "themes": ["identity", "resilience", "family"]
    },
]

TRAVEL = [
    {
        "id": 1,
        "destination": "Kyoto, Japan",
        "type": "cultural",
        "climate": "temperate",
        "budget": "medium",
        "pace": "relaxed",
        "duration": "week",
        "crowd": "moderate",
        "description": "Ancient temples, bamboo forests, and geisha districts blend tradition with modernity.",
        "highlights": ["Fushimi Inari Shrine", "Arashiyama Bamboo Grove", "Gion District", "Kinkaku-ji"],
        "best_for": ["culture", "photography", "history", "food"],
        "cuisine": "Japanese",
        "language": "Japanese",
        "visa_ease": "easy",
        "tags": ["temples", "zen", "cherry-blossom", "tradition"]
    },
    {
        "id": 2,
        "destination": "Amalfi Coast, Italy",
        "type": "scenic",
        "climate": "mediterranean",
        "budget": "high",
        "pace": "relaxed",
        "duration": "week",
        "crowd": "busy",
        "description": "Dramatic cliffs, turquoise waters, and colorful villages along Italy's southern coast.",
        "highlights": ["Positano", "Ravello Gardens", "Boat tours", "Pompeii"],
        "best_for": ["romance", "scenery", "food", "photography"],
        "cuisine": "Italian",
        "language": "Italian",
        "visa_ease": "easy",
        "tags": ["cliffs", "sea", "villages", "pasta"]
    },
    {
        "id": 3,
        "destination": "Patagonia, Argentina/Chile",
        "type": "adventure",
        "climate": "cold",
        "budget": "high",
        "pace": "active",
        "duration": "two-weeks",
        "crowd": "sparse",
        "description": "Raw wilderness at the end of the world: glaciers, peaks, and untamed nature.",
        "highlights": ["Torres del Paine", "Perito Moreno Glacier", "Los Glaciares", "El Chaltén"],
        "best_for": ["hiking", "nature", "photography", "adventure"],
        "cuisine": "South American",
        "language": "Spanish",
        "visa_ease": "easy",
        "tags": ["glaciers", "hiking", "wilderness", "mountains"]
    },
    {
        "id": 4,
        "destination": "Marrakech, Morocco",
        "type": "cultural",
        "climate": "hot",
        "budget": "low",
        "pace": "active",
        "duration": "weekend",
        "crowd": "busy",
        "description": "A sensory explosion of souks, riads, spices, and ancient medinas.",
        "highlights": ["Djemaa el-Fna", "Majorelle Garden", "Medina souks", "Atlas Mountains day trip"],
        "best_for": ["culture", "food", "shopping", "photography"],
        "cuisine": "Moroccan",
        "language": "Arabic/French",
        "visa_ease": "easy",
        "tags": ["souk", "spices", "riad", "desert"]
    },
    {
        "id": 5,
        "destination": "Iceland",
        "type": "adventure",
        "climate": "cold",
        "budget": "high",
        "pace": "active",
        "duration": "week",
        "crowd": "sparse",
        "description": "Land of fire and ice: geysers, waterfalls, northern lights, and volcanic landscapes.",
        "highlights": ["Golden Circle", "Northern Lights", "Blue Lagoon", "Jökulsárlón"],
        "best_for": ["nature", "adventure", "photography", "unique-experience"],
        "cuisine": "Nordic",
        "language": "Icelandic",
        "visa_ease": "easy",
        "tags": ["aurora", "waterfalls", "geysers", "midnight-sun"]
    },
    {
        "id": 6,
        "destination": "Bali, Indonesia",
        "type": "wellness",
        "climate": "tropical",
        "budget": "low",
        "pace": "relaxed",
        "duration": "two-weeks",
        "crowd": "busy",
        "description": "Spiritual retreats, rice terraces, surfing, and vibrant Hindu culture.",
        "highlights": ["Ubud Rice Terraces", "Tanah Lot Temple", "Seminyak Beach", "Mount Batur"],
        "best_for": ["wellness", "culture", "food", "nature"],
        "cuisine": "Balinese",
        "language": "Balinese/Indonesian",
        "visa_ease": "easy",
        "tags": ["spiritual", "surf", "rice-fields", "temples"]
    },
    {
        "id": 7,
        "destination": "New York City, USA",
        "type": "urban",
        "climate": "temperate",
        "budget": "high",
        "pace": "fast",
        "duration": "weekend",
        "crowd": "very-busy",
        "description": "The city that never sleeps — museums, Broadway, world-class food and iconic skylines.",
        "highlights": ["Central Park", "MoMA", "Brooklyn Bridge", "High Line"],
        "best_for": ["urban", "culture", "food", "nightlife"],
        "cuisine": "World",
        "language": "English",
        "visa_ease": "medium",
        "tags": ["skyscrapers", "broadway", "pizza", "fashion"]
    },
    {
        "id": 8,
        "destination": "Serengeti, Tanzania",
        "type": "adventure",
        "climate": "hot",
        "budget": "high",
        "pace": "relaxed",
        "duration": "week",
        "crowd": "sparse",
        "description": "Witness the Great Migration and Africa's Big Five in their natural habitat.",
        "highlights": ["Great Migration", "Ngorongoro Crater", "Maasai Village", "Hot air balloon safari"],
        "best_for": ["wildlife", "nature", "photography", "unique-experience"],
        "cuisine": "East African",
        "language": "Swahili",
        "visa_ease": "medium",
        "tags": ["safari", "wildlife", "africa", "migration"]
    },
    {
        "id": 9,
        "destination": "Prague, Czech Republic",
        "type": "cultural",
        "climate": "temperate",
        "budget": "low",
        "pace": "relaxed",
        "duration": "weekend",
        "crowd": "busy",
        "description": "A fairytale city of gothic spires, baroque churches, and lively beer culture.",
        "highlights": ["Prague Castle", "Charles Bridge", "Old Town Square", "Beer halls"],
        "best_for": ["culture", "history", "nightlife", "food"],
        "cuisine": "Czech",
        "language": "Czech",
        "visa_ease": "easy",
        "tags": ["gothic", "castle", "beer", "medieval"]
    },
    {
        "id": 10,
        "destination": "Maldives",
        "type": "beach",
        "climate": "tropical",
        "budget": "high",
        "pace": "relaxed",
        "duration": "week",
        "crowd": "sparse",
        "description": "Crystal-clear lagoons, overwater bungalows, and world-class diving in the Indian Ocean.",
        "highlights": ["Snorkeling with manta rays", "Overwater bungalows", "Bioluminescent beaches", "Sunset cruises"],
        "best_for": ["romance", "relaxation", "diving", "unique-experience"],
        "cuisine": "Maldivian/International",
        "language": "Dhivehi",
        "visa_ease": "easy",
        "tags": ["overwater", "diving", "luxury", "coral"]
    },
    {
        "id": 11,
        "destination": "Lisbon, Portugal",
        "type": "urban",
        "climate": "mediterranean",
        "budget": "medium",
        "pace": "relaxed",
        "duration": "weekend",
        "crowd": "moderate",
        "description": "Hilly streets, vintage trams, Fado music, and extraordinary seafood.",
        "highlights": ["Belém Tower", "Alfama district", "Tram 28", "Sintra day trip"],
        "best_for": ["culture", "food", "photography", "history"],
        "cuisine": "Portuguese",
        "language": "Portuguese",
        "visa_ease": "easy",
        "tags": ["trams", "fado", "tiles", "pastel"]
    },
    {
        "id": 12,
        "destination": "Machu Picchu, Peru",
        "type": "adventure",
        "climate": "temperate",
        "budget": "medium",
        "pace": "active",
        "duration": "week",
        "crowd": "moderate",
        "description": "The legendary Inca citadel perched in the clouds above the Sacred Valley.",
        "highlights": ["Inca Trail hike", "Sun Gate", "Huayna Picchu", "Cusco city"],
        "best_for": ["history", "adventure", "photography", "hiking"],
        "cuisine": "Peruvian",
        "language": "Spanish",
        "visa_ease": "easy",
        "tags": ["inca", "ruins", "mountains", "history"]
    },
]
